### ISSUE TITLE
NullPointerException.

### ISSUE THREAD

**Issue by YYYSSSHHH** [SecUSo/privacy-friendly-qr-scanner#107]
**Environment Info：**
APK Version: 3.1.0 (20)
Android simulator version: 6.0.1

**Repro Steps：**

1.Click the "QR Generator"button.
2.Click the "Phone number" button.
3.Click the "GENERATE" button, and then the stack trace logs "NullPointerException".

![final](https://user-images.githubusercontent.com/55122523/129847809-7f010050-eb2c-4f20-82ec-d9222828cb37.png)

**The Stack Trace:**
FATAL EXCEPTION: main
Process: com.secuso.privacyFriendlyCodeScanner, PID: 7184
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.secuso.privacyFriendlyCodeScanner/com.secuso.privacyfriendlycodescanner.qrscanner.ui.activities.generator.QrGeneratorDisplayActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2443)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2503)
	at android.app.ActivityThread.-wrap11(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
	at com.secuso.privacyfriendlycodescanner.qrscanner.generator.QRGeneratorUtils.writeToFile(QRGeneratorUtils.java:169)
	at com.secuso.privacyfriendlycodescanner.qrscanner.generator.QRGeneratorUtils.cacheImage(QRGeneratorUtils.java:61)
	at com.secuso.privacyfriendlycodescanner.qrscanner.generator.QRGeneratorUtils.createImage(QRGeneratorUtils.java:97)
	at com.secuso.privacyfriendlycodescanner.qrscanner.ui.activities.generator.QrGeneratorDisplayActivity.onCreate(QrGeneratorDisplayActivity.java:42)
	at android.app.Activity.performCreate(Activity.java:6279)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2396)
	... 10 more

**Do you confirm this exception? Thanks.**

**Comment by Kamuno** [comment]
Closed via #108
